### ISSUE TITLE
Crash within WinDivertParseResult initializer

### ISSUE THREAD

**Issue by TechnikEmpire** [TechnikEmpire/WinDivertSharp#3]
```C#
2018-08-17 19:14:32.404 -05:00 [Error] Could not load type 'WinDivertParseResult' from assembly 'WinDivertSharp, Version=1.4.3.2, Culture=neutral, PublicKeyToken=null'.   at CitadelCore.Windows.Diversion.WindowsDiverter.RunDiversion()
   at CitadelCore.Windows.Diversion.WindowsDiverter.<Start>b__26_0()
	 From WindowsDiverter.cs::Start() #261
2018-08-17 19:14:32.404 -05:00 [Error] Could not load type 'WinDivertParseResult' from assembly 'WinDivertSharp, Version=1.4.3.2, Culture=neutral, PublicKeyToken=null'.   at CitadelCore.Windows.Diversion.WindowsDiverter.RunDiversion()
   at CitadelCore.Windows.Diversion.WindowsDiverter.<Start>b__26_0()
	 From WindowsDiverter.cs::Start() #261
2018-08-17 19:14:32.404 -05:00 [Error] Could not load type 'WinDivertParseResult' from assembly 'WinDivertSharp, Version=1.4.3.2, Culture=neutral, PublicKeyToken=null'.   at CitadelCore.Windows.Diversion.WindowsDiverter.RunDiversion()
   at CitadelCore.Windows.Diversion.WindowsDiverter.<Start>b__26_0()
	 From WindowsDiverter.cs::Start() #261
2018-08-17 19:14:32.404 -05:00 [Error] Could not load type 'WinDivertParseResult' from assembly 'WinDivertSharp, Version=1.4.3.2, Culture=neutral, PublicKeyToken=null'.   at CitadelCore.Windows.Diversion.WindowsDiverter.RunDiversion()
   at CitadelCore.Windows.Diversion.WindowsDiverter.<Start>b__26_0()
	 From WindowsDiverter.cs::Start() #261
```

**Comment by vdhong** [comment]
Hello,
How about the fixing of this bug?

**Comment by TechnikEmpire** [comment]
Have you experienced this?

**Comment by vdhong** [comment]
I fall in to this error when I use CitadelCore.Windows for my project but CitadelCore.Windows.Example project can work so I copy all dll from sample project to my bin folder and then my application can work now. I don't know why.

**Comment by TechnikEmpire** [comment]
Ok thanks for reporting. I think there's a problem with binding redirects here. I think what I might do is just change this project and WinDivertSharp to target .net full 4.7 to see if the issue goes away. Vista is discontinued anyway so I see no reason not to just target 4.7 full. Let me know what you think of that.

**Comment by vdhong** [comment]
I think you should not set target to 4.7 because you can try my way above to find out why.

**Comment by TechnikEmpire** [comment]
Run the same program longer, it will still crash eventually with the same error.

**Comment by vdhong** [comment]
I run my program longer, it can work ok but it show warning 
`WARN: Failed to add HTTP header with key Accept-Encoding and with value gzip, deflate, br.        FilterHttpResponseHandler.cs::Handle() #293`

**Comment by TechnikEmpire** [comment]
@vdhong That warning can be safely ignored. I thought I removed it.

**Comment by vdhong** [comment]
I remove NutGet packages Citadelcore.Windows then I download CitadelCore and CitadelCore.Windows then I add them to my solution and reference them in my project. Now my app can work. 
You can try this way to find out more about this bug. I think this error maybe because of dll from NutGet.

**Comment by TechnikEmpire** [comment]
Hmm that's quite interesting. Thanks. I'll get back to you.

**Comment by vdhong** [comment]
Thank you!

**Comment by TechnikEmpire** [comment]
I wonder if you're right and this is simply a matter of the Nuget dll being broken. Am looking into this.

**Comment by TechnikEmpire** [comment]
This should be fixed by fa44ad8 , but I'll leave this open until we can confirm this.

**Comment by TechnikEmpire** [comment]
Stupid github. Reopening.

**Comment by TechnikEmpire** [comment]
@vdhong Try using the CitadelCore.Windows package directly from nuget again as of version 3.0.14. This issue should be gone now if my theory about the cause is correct.

**Comment by TechnikEmpire** [comment]
Oh make sure that you add WinDivertSharp to your project manually as well as CitadelCore.Windows. The package system will not properly copy the native dlls to your ouput directory without this work around. This is a nuget issue as far as I can tell.

**Comment by TechnikEmpire** [comment]
This was fixed in the above commit.
